#!/usr/bin/env php
<?php

require_once __DIR__.'/../vendor/autoload.php';
use Symfony\Component\Console\Application;
use App\Command\NotifyCommand;

$application = new Application();
$application -> add(new NotifyCommand());
$application->run();